[package]
name = "simple-task"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", features = ["widget-calendar"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
